name: pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
   
    runs-on: ubuntu-latest

    
    steps:
    
    - name: Step 1 Checkout Project  
      uses: actions/checkout@v3

    
    - name: Step 2 Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
        bundler-cache: true 
    
    - name: Step 3 Execute test
      run:
          bundle exec cucumber -p ci          

    
    - name: Step 4 Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: ./reports/report.html