name: ci




on:

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]




  #executar Manualmente na aba Action

  workflow_dispatch:




permissions:

  contents: read




jobs:

  test:




    # Executa na ultima versão do ubuntu

    runs-on: ubuntu-latest




    # Steps são os passo a passo para executar o projeto

    steps:

    # Clona o projeto para executar no action

    - name: Step 1 Checkout Project  

      uses: actions/checkout@v3




    # Configuração do Ruby e das dependências

    - name: Step 2 Setup Ruby

      uses: ruby/setup-ruby@v1

      with:

        ruby-version: '3.1.2'

        bundler-cache: true # executa 'bundle install' e armazena em cache as gems instaladas




    # Excecução dos testes no navegador web sem interface chrome_headless

    - name: Step 3 Execute test

      run:

          bundle exec cucumber -p ci          




    # Grava o relatório do resultado do teste

    - name: Step 4 Archive production artifacts

      uses: actions/upload-artifact@v3

      with:

        name: reports

        path: ./reports/report.html